import Head from "next/head";
import Image from "next/image";
import styles from "./style.module.less";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sharing Session</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to The <a href="/">Sharing Session!</a>
        </h1>
      </main>

      <footer className={styles.footer}>
        Powered by :
        <span>
          <b> Team Sharing Session</b>
        </span>
      </footer>
    </div>
  );
}
